"""Built-in process-backed capability profiles. No specialist reasoning lives here."""
from __future__ import annotations

from typing import Any


def build_task_profiles(child: str) -> dict[str, dict[str, Any]]:
    return {
        "memory_graph_neural": {
            "kind": "subprocess",
            "command": ["python", "memory_graph.py", "--phase", "neural"],
            "module": "memory_graph",
            "priority": 90,
            "memory_class": "high",
            "cpu_class": "high",
            "gpu_class": "none",
            "exclusive_group": "memory_recall",
        },
        "deep_recall_step": {
            "kind": "step",
            "module": "deep_recall",
            "priority": 70,
            "memory_class": "high",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "memory_recall",
        },
        "dreamstate_run": {
            "kind": "subprocess",
            "command": ["python", "dreamstate.py"],
            "module": "dreamstate",
            "priority": 84,
            "memory_class": "medium",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "conscious_mode",
        },
        "storage_migration_step": {
            "kind": "subprocess",
            "command": ["python", "storage_migration.py", "--resume-managed"],
            "module": "storage_migration",
            "priority": 99,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "memory_recall",
            "max_runtime_sec": 600.0,
        },
        "experience_archive_step": {
            "kind": "subprocess",
            "command": ["python", "experience_maintenance.py"],
            "module": "experience_archive",
            "priority": 61,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "memory_recall",
            "max_runtime_sec": 150.0,
        },
        "memory_reconciliation_step": {
            "kind": "subprocess",
            "command": ["python", "memory_reconciliation.py", "--max-new-records", "50000", "--max-seconds", "30"],
            "module": "memory_reconciliation",
            "priority": 62,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "memory_recall",
            "max_runtime_sec": 120.0,
        },
    
        "meditation_state_run": {
            "kind": "subprocess",
            "command": ["python", "meditation_state.py"],
            "module": "meditation_state",
            "priority": 82,
            "memory_class": "medium",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "conscious_mode",
        },
        "emotion_engine_run": {
            "kind": "subprocess",
            "command": ["python", "emotion_engine.py"],
            "module": "emotion_engine",
            "priority": 72,
            "memory_class": "low",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "instinct_engine_run": {
            "kind": "subprocess",
            "command": ["python", "instinct_engine.py"],
            "module": "instinct_engine",
            "priority": 74,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "early_comm_run": {
            "kind": "subprocess",
            "command": ["python", "early_comm.py"],
            "module": "early_comm",
            "priority": 58,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "predictive_layer_run": {
            "kind": "subprocess",
            "command": ["python", "predictive_layer.py"],
            "module": "predictive_layer",
            "priority": 76,
            "memory_class": "medium",
            "cpu_class": "high",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "logic_engine_run": {
            "kind": "subprocess",
            "command": ["python", "logic_engine.py"],
            "module": "logic_engine",
            "priority": 76,
            "memory_class": "medium",
            "cpu_class": "high",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "meaning_map_refresh": {
            "kind": "subprocess",
            "command": ["python", "meaning_map.py"],
            "module": "meaning_map",
            "priority": 78,
            "memory_class": "high",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "map_build",
        },
        "neural_graph_refresh": {
            "kind": "subprocess",
            "command": ["python", "neural_graph.py"],
            "module": "neural_graph",
            "priority": 74,
            "memory_class": "medium",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "map_build",
        },
        "logic_map_refresh": {
            "kind": "subprocess",
            "command": ["python", "logic_map_builder.py"],
            "module": "logic_map",
            "priority": 76,
            "memory_class": "high",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "map_build",
        },
        "emotion_map_refresh": {
            "kind": "subprocess",
            "command": ["python", "emotion_map.py"],
            "module": "emotion_map",
            "priority": 72,
            "memory_class": "medium",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "map_build",
        },
        "who_am_i_run": {
            "kind": "subprocess",
            "command": ["python", "who_am_i.py"],
            "module": "who_am_i",
            "priority": 68,
            "memory_class": "low",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "trauma_processor_run": {
            "kind": "subprocess",
            "command": ["python", "trauma_processor.py"],
            "module": "trauma_processor",
            "priority": 80,
            "memory_class": "medium",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "boredom_state_run": {
            "kind": "subprocess",
            "command": ["python", "boredom_state.py"],
            "module": "boredom_state",
            "priority": 54,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "",
        },
        "paint_window_open": {
            "kind": "subprocess",
            "command": ["python", "paint_runtime.py"],
            "module": "paint_window",
            "priority": 52,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "creative_ui",
        },
        "file_explorer_open": {
            "kind": "subprocess",
            "command": ["python", "ina_file_explorer.py", "--child", str(child)],
            "module": "ina_file_explorer",
            "priority": 51,
            "memory_class": "low",
            "cpu_class": "low",
            "gpu_class": "none",
            "exclusive_group": "creative_ui",
        },
        "daw_window_open": {
            "kind": "subprocess",
            "command": ["python", "daw_window.py", "--child", str(child)],
            "module": "daw_window",
            "priority": 53,
            "memory_class": "low",
            "cpu_class": "medium",
            "gpu_class": "none",
            "exclusive_group": "creative_ui",
        },
    }
